
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrtirloetmulgmdxnusl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxydGlybG9ldG11bGdtZHhudXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzAxODYsImV4cCI6MjA2MTQ0NjE4Nn0.a1PkDU3cFd_BWNtf76m5a_NM5JCc9gO5xgN_tzJpquM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
